# OrderPortal: Settings file, to be edited for your instance.

# This file changes the default values defined in the 'settings' dictionary
# in the '__init__.py' file.

### You should copy this file to 'settings.yaml', which is
### the file that 'app_orderportal.py' looks for by default.

# Official URL to the portal; access from the outside world.
BASE_URL: 'http://my-domain.com/'
# The following may be useful for testing on a laptop:
# BASE_URL: 'http://localhost:8880/'

# Port for the tornado server; may be different from BASE_URL if proxy is used.
PORT: 8880

# CouchDB server
DATABASE_SERVER:   'http://localhost:5984/'
DATABASE_NAME:     'orderportal'
DATABASE_ACCOUNT:  'orderportal_account'
DATABASE_PASSWORD: 'Change this to CouchDB account password'

# Logging and debug
TORNADO_DEBUG: true
LOGGING_DEBUG: true
LOGGING_FILEPATH: '/var/log/orderportal/debug.log'

# Login; these *must* be changed for your instance.
COOKIE_SECRET: 'Change this to a long string of random characters.'
PASSWORD_SALT: 'Change this to a long string of random characters.'

# The name of your instance, and support email address.
SITE_NAME:          'My Order Portal'
SITE_SUPPORT_EMAIL: 'my.email@my-domain.com'

# The site directory; contains status icons, logos, definition YAML files.
SITE_DIR:           '{ROOT_DIR}/my-site'

# The icon files must be in the SITE_DIR; absolute file path is not allowed.
SITE_FAVICON:     'orderportal32.png'
SITE_NAVBAR_ICON: 'orderportal32.png'
SITE_HOME_ICON:   'orderportal144.png'

# Account setup; email message templates.
ACCOUNT_MESSAGES_FILEPATH: '{SITE_DIR}/account_messages.yaml'

# Account registration input flags.
ACCOUNT_INVOICE_INFO: true
ACCOUNT_FUNDER_INFO: true
ACCOUNT_DEFAULT_COUNTRY_CODES: 'SE'

# Order status, transition, messages definition files
ORDER_STATUSES_FILEPATH:    '{SITE_DIR}/order_statuses.yaml'
ORDER_TRANSITIONS_FILEPATH: '{SITE_DIR}/order_transitions.yaml'
ORDER_MESSAGES_FILEPATH:    '{SITE_DIR}/order_messages.yaml'

# Allow users to set tags on orders.
ORDER_USER_TAGS: true

# Define in order to use sequentially numbered order identifiers.
ORDER_IDENTIFIER_FORMAT: 'MY{0:=05d}'
ORDER_IDENTIFIER_REGEXP: 'MY\d+'

# The statuses to show in the orders list.
# The statuses must be defined in the ORDER_STATUSES_FILEPATH file.
ORDERS_LIST_STATUSES:
  - submitted
  - accepted
  - processing
  - closed

# University symbols (abbreviations), names and rank in list.
# Optional, may be set to null.
UNIVERSITIES_FILEPATH: '{SITE_DIR}/swedish_universities.yaml'

# Country names and codes. Optional, may be set to null.
COUNTRY_CODES_FILEPATH: '{SITE_DIR}/country_codes.yaml'

# Subject codes, terms in a hierarchy. Optional, may be set to null.
SUBJECT_TERMS_FILEPATH: '{SITE_DIR}/subject_terms.yaml'

# Messages; email server info.
MESSAGE_SENDER_EMAIL: '"OrderPortal Support" <support@my-domain.com>'
EMAIL:
  HOST: 'localhost'

# Display settings.
DISPLAY_NEWS: true
DISPLAY_EVENTS: true
